// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//
// Toggles the Claude Code status line — the bar Claude Code renders at the
// bottom of the terminal with model / context usage / cost / rate limits.
//
// Claude Code exposes no on-off switch of its own: the bar exists only when
// `statusLine` in ~/.claude/settings.json names a command, and Claude Code
// prints whatever that command writes to stdout. So enabling means writing
// our own PowerShell script and pointing `statusLine` at it; disabling means
// removing the key again. Every other key in settings.json is preserved.
//
// Docs: https://code.claude.com/docs/en/statusline

#include "pch.h"
#include "CTuxClaudeStatusLine.h"
#include "CTuxSettings.h"
#include <json/json.h>
#include <fstream>
#include <sstream>
#include <filesystem>

namespace ClickTerminal::ClaudeStatusLine
{
    namespace
    {
        // Substring that identifies the statusLine command as ours.
        constexpr const char* kScriptMarker = "ctux-statusline.ps1";

        std::string WideToNarrow(const std::wstring& ws)
        {
            if (ws.empty()) return {};
            int len = WideCharToMultiByte(CP_UTF8, 0, ws.c_str(), -1, nullptr, 0, nullptr, nullptr);
            std::string r(len - 1, '\0');
            WideCharToMultiByte(CP_UTF8, 0, ws.c_str(), -1, r.data(), len, nullptr, nullptr);
            return r;
        }

        // Git Bash (which Claude Code prefers on Windows when installed) eats
        // unquoted backslashes in the command string, so paths must use "/".
        std::string ToForwardSlashUtf8(const std::wstring& path)
        {
            auto s = WideToNarrow(path);
            for (auto& c : s)
                if (c == '\\') c = '/';
            return s;
        }

        // Missing and Empty are both "nothing configured yet"; only Malformed
        // is an error worth stopping for.
        enum class ReadResult
        {
            Missing,
            Empty,
            Ok,
            Malformed,
        };

        ReadResult ReadJsonFile(const std::wstring& path, Json::Value& out)
        {
            std::ifstream f(path, std::ios::binary);
            if (!f.is_open()) return ReadResult::Missing;

            std::ostringstream ss;
            ss << f.rdbuf();
            auto text = ss.str();

            // Strip a UTF-8 BOM — jsoncpp chokes on it.
            if (text.size() >= 3 &&
                static_cast<unsigned char>(text[0]) == 0xEF &&
                static_cast<unsigned char>(text[1]) == 0xBB &&
                static_cast<unsigned char>(text[2]) == 0xBF)
                text.erase(0, 3);

            if (text.find_first_not_of(" \t\r\n") == std::string::npos)
                return ReadResult::Empty;

            Json::CharReaderBuilder builder;
            builder["allowComments"] = true;
            std::string errs;
            std::istringstream iss(text);
            if (!Json::parseFromStream(builder, iss, &out, &errs) || !out.isObject())
                return ReadResult::Malformed;
            return ReadResult::Ok;
        }

        bool WriteJsonFile(const std::wstring& path, const Json::Value& root)
        {
            Json::StreamWriterBuilder wb;
            wb["indentation"] = "  ";
            auto json = Json::writeString(wb, root);

            std::ofstream f(path, std::ios::binary | std::ios::trunc);
            if (!f.is_open()) return false;
            f.write(json.c_str(), static_cast<std::streamsize>(json.size()));
            return f.good();
        }

        std::wstring BackupPath()
        {
            auto dir = CTuxSettings::GetDefaultDir();
            if (dir.empty()) return {};
            return dir + L"\\ctux-statusline-backup.json";
        }

        // The generated script. Kept pure ASCII on purpose: the bar glyphs are
        // built from code points at runtime, so the file needs no BOM and
        // survives whatever encoding a text editor writes it back as.
        constexpr const char* kScriptBody = R"PS(# ClickTerminal (CTux) status line for Claude Code.
#
# Generated by ClickTerminal: Settings > General > Claude Code Status Line.
# Rewritten every time that toggle is switched on, so local edits are lost.
# Turning the toggle off removes the "statusLine" entry from
# ~/.claude/settings.json but leaves this file in place.
#
# Input format: https://code.claude.com/docs/en/statusline

$ErrorActionPreference = 'SilentlyContinue'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

$raw = [Console]::In.ReadToEnd()
if (-not $raw) { exit 0 }
$d = $raw | ConvertFrom-Json
if (-not $d) { exit 0 }

# Built from code points so this file stays ASCII-only.
$BLOCK_FULL  = [string][char]0x2593
$BLOCK_EMPTY = [string][char]0x2591

$ESC    = [string][char]27
$RESET  = "$ESC[0m"
$DIM    = "$ESC[2m"
$CYAN   = "$ESC[36m"
$GREEN  = "$ESC[32m"
$YELLOW = "$ESC[33m"
$RED    = "$ESC[31m"

function Format-Tokens([double]$n) {
    if ($n -ge 1000000) { return ('{0:0.#}M' -f ($n / 1000000)) }
    if ($n -ge 1000)    { return ('{0:0}K'   -f ($n / 1000)) }
    return ('{0:0}' -f $n)
}

function Format-Reset([double]$epoch) {
    if (-not $epoch) { return '' }
    $left = $epoch - [double][DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    if ($left -le 0) { return '' }
    $h = [int][math]::Floor($left / 3600)
    if ($h -ge 24) { return ('{0}d{1}h' -f [int][math]::Floor($h / 24), ($h % 24)) }
    if ($h -ge 1)  { return ('{0}h' -f $h) }
    return ('{0}m' -f [int][math]::Floor($left / 60))
}

$parts = @()

# --- model ---------------------------------------------------------------
$model = $d.model.display_name
if ($model) { $parts += ($CYAN + $model + $RESET) }

# --- context window ------------------------------------------------------
$cw = $d.context_window
if ($cw) {
    $pct = 0
    if ($null -ne $cw.used_percentage) { $pct = [int][math]::Floor([double]$cw.used_percentage) }
    if ($pct -lt 0)   { $pct = 0 }
    if ($pct -gt 100) { $pct = 100 }

    $width  = 10
    $filled = [int][math]::Floor($pct * $width / 100)
    $bar    = ($BLOCK_FULL * $filled) + ($BLOCK_EMPTY * ($width - $filled))

    $color = $GREEN
    if ($pct -ge 75)      { $color = $RED }
    elseif ($pct -ge 50)  { $color = $YELLOW }

    $tokens = ''
    $size = [double]$cw.context_window_size
    if ($size -gt 0) {
        $used = [double]$cw.total_input_tokens + [double]$cw.total_output_tokens
        $tokens = ' (' + (Format-Tokens $used) + '/' + (Format-Tokens $size) + ')'
    }

    $parts += ($color + $bar + ' ' + $pct + '%' + $RESET + $DIM + $tokens + $RESET)
}

# --- session cost --------------------------------------------------------
if ($null -ne $d.cost.total_cost_usd) {
    $parts += ('$' + ('{0:N2}' -f [double]$d.cost.total_cost_usd))
}

# --- rate limit windows --------------------------------------------------
$limits = @()
if ($null -ne $d.rate_limits.five_hour.used_percentage) {
    $r = Format-Reset ([double]$d.rate_limits.five_hour.resets_at)
    $limits += ('5h:' + [int]$d.rate_limits.five_hour.used_percentage + '%' + $(if ($r) { "($r)" } else { '' }))
}
if ($null -ne $d.rate_limits.seven_day.used_percentage) {
    $r = Format-Reset ([double]$d.rate_limits.seven_day.resets_at)
    $limits += ('7d:' + [int]$d.rate_limits.seven_day.used_percentage + '%' + $(if ($r) { "($r)" } else { '' }))
}
if ($limits.Count -gt 0) { $parts += ($DIM + ($limits -join ' ') + $RESET) }

Write-Host ($parts -join ($DIM + ' | ' + $RESET))
)PS";
    }

    // ---------------------------------------------------------------------
    // Paths
    // ---------------------------------------------------------------------
    std::wstring ClaudeDir()
    {
        wchar_t profile[MAX_PATH] = {};
        DWORD len = GetEnvironmentVariableW(L"USERPROFILE", profile, MAX_PATH);
        if (len == 0 || len >= MAX_PATH) return {};
        return std::wstring(profile, len) + L"\\.claude";
    }

    std::wstring SettingsPath()
    {
        auto dir = ClaudeDir();
        return dir.empty() ? std::wstring{} : dir + L"\\settings.json";
    }

    std::wstring ScriptPath()
    {
        auto dir = ClaudeDir();
        return dir.empty() ? std::wstring{} : dir + L"\\ctux-statusline.ps1";
    }

    // ---------------------------------------------------------------------
    // State
    // ---------------------------------------------------------------------
    namespace
    {
        // Returns the current statusLine command, or empty when there is none.
        std::string CurrentCommand()
        {
            auto path = SettingsPath();
            if (path.empty()) return {};

            Json::Value root;
            if (ReadJsonFile(path, root) != ReadResult::Ok) return {};

            const auto& sl = root["statusLine"];
            if (!sl.isObject()) return {};
            return sl.get("command", "").asString();
        }
    }

    bool IsEnabled()
    {
        auto cmd = CurrentCommand();
        return !cmd.empty() && cmd.find(kScriptMarker) != std::string::npos;
    }

    bool HasForeignStatusLine()
    {
        auto cmd = CurrentCommand();
        return !cmd.empty() && cmd.find(kScriptMarker) == std::string::npos;
    }

    // ---------------------------------------------------------------------
    // Enable / Disable
    // ---------------------------------------------------------------------
    bool Enable(std::wstring& error)
    {
        auto dir = ClaudeDir();
        if (dir.empty())
        {
            error = L"USERPROFILE is not set — cannot locate the .claude folder.";
            return false;
        }

        std::error_code ec;
        std::filesystem::create_directories(dir, ec);
        if (ec)
        {
            error = L"Could not create " + dir;
            return false;
        }

        // 1. Write (or refresh) the script.
        {
            std::ofstream f(ScriptPath(), std::ios::binary | std::ios::trunc);
            if (!f.is_open())
            {
                error = L"Could not write " + ScriptPath();
                return false;
            }
            f << kScriptBody;
            if (!f.good())
            {
                error = L"Could not write " + ScriptPath();
                return false;
            }
        }

        // 2. Merge statusLine into settings.json, keeping every other key.
        auto settingsPath = SettingsPath();
        Json::Value root(Json::objectValue);
        if (ReadJsonFile(settingsPath, root) == ReadResult::Malformed)
        {
            error = L"~/.claude/settings.json is not valid JSON — fix it first.";
            return false;
        }
        if (!root.isObject()) root = Json::Value(Json::objectValue);

        // Back up a status line that isn't ours, so Disable can restore it.
        if (root["statusLine"].isObject())
        {
            auto existing = root["statusLine"].get("command", "").asString();
            if (existing.find(kScriptMarker) == std::string::npos)
            {
                auto backup = BackupPath();
                if (!backup.empty()) WriteJsonFile(backup, root["statusLine"]);
            }
        }

        Json::Value sl(Json::objectValue);
        sl["type"] = "command";
        sl["command"] = "powershell -NoProfile -ExecutionPolicy Bypass -File \"" +
                        ToForwardSlashUtf8(ScriptPath()) + "\"";
        sl["padding"] = 0;
        root["statusLine"] = sl;

        if (!WriteJsonFile(settingsPath, root))
        {
            error = L"Could not write " + settingsPath;
            return false;
        }

        error.clear();
        return true;
    }

    bool Disable(std::wstring& error)
    {
        auto settingsPath = SettingsPath();
        if (settingsPath.empty())
        {
            error = L"USERPROFILE is not set — cannot locate the .claude folder.";
            return false;
        }

        Json::Value root;
        if (ReadJsonFile(settingsPath, root) != ReadResult::Ok)
        {
            // No settings file, empty, or unparseable — nothing to turn off.
            error.clear();
            return true;
        }
        if (!root.isMember("statusLine"))
        {
            error.clear();
            return true;
        }

        // Restore a status line we displaced when we were switched on.
        Json::Value backup;
        auto backupPath = BackupPath();
        if (!backupPath.empty() && ReadJsonFile(backupPath, backup) == ReadResult::Ok)
        {
            root["statusLine"] = backup;
            std::error_code ec;
            std::filesystem::remove(backupPath, ec);
        }
        else
        {
            root.removeMember("statusLine");
        }

        if (!WriteJsonFile(settingsPath, root))
        {
            error = L"Could not write " + settingsPath;
            return false;
        }

        error.clear();
        return true;
    }
}
